# Generated by Django 6.0.1 on 2026-05-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('DONE', 'Done'), ('IN_PROGRESS', 'In Progress')], max_length=25)),
                ('marked', models.BooleanField(default=False)),
            ],
        ),
    ]
