# Generated by Django 6.0.1 on 2026-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('IMPORTANT', 'Important'), ('FUN', 'Fun'), ('SMALL', 'Small')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('DONE', 'Done'), ('IN_PROGRESS', 'In Progress')], default='TODO', max_length=25),
        ),
    ]
