# Generated by Django 6.0.5 on 2026-05-25 11:10

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category_alter_task_notes_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('rank',), name='unique_rank_deferrable'),
        ),
    ]
