# Generated by Django 6.0.5 on 2026-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_rank_task_unique_rank_deferrable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('IMPORTANT', 'Important'), ('FUN', 'Fun'), ('SMALL', 'Small'), ('URGENT', 'Urgent')], max_length=25, null=True),
        ),
    ]
