# Generated by Django 6.0.7 on 2026-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('IMPORTANT', 'Important'), ('FUN', 'Fun'), ('URGENT', 'Urgent'), ('SMALL', 'Small')], max_length=25, null=True),
        ),
    ]
